version: "3"

services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.3:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.3:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
